#!/bin/bash
#SBATCH -p general
#SBATCH -J HapDup
##SBATCH --ntasks=1
#SBATCH --mem 110Gb
#SBATCH --cpus-per-task=24
#SBATCH -t 8-0:00:00
#SBATCH --output hapdup_%j.log


module purge
. ${PROJ}/software/anaconda3/etc/profile.d/conda.sh
conda deactivate
conda deactivate

ml minimap2/2.17 samtools/1.15


REF="${PROJ}/genomes/Lu_longipalpis_male_1.0.fa"
READS="/pine/scr/j/r/jrwang/assembly/lutzomyia/data/longipalpis_female_211208.fastq.gz"


mkdir $SCR/HapDup_female
cd $SCR/HapDup_female

minimap2 -ax map-ont -t 24 $REF $READS | samtools sort -@ 24 -m 10G > lr_mapping.bam
samtools index -@ 24 mapping.bam


# run HapDup
conda activate hapdup
${PROJ}/software/hapdup/hapdup.py --assembly $REF --bam lr_mapping.bam --out-dir hapdup -t 24 --rtype ont


##### run SV analyses
## note: possible issue with numpy in hapdup environment  (and base)

${PROJ}/software/dipdiff/dipdiff.py --reference $REF --pat hapdup/haplotype_1.fasta --mat hapdup/haplotype_1.fasta --out-dir SV_out -t 24


# visualize chromosome 1
unwrap_fasta haplotype_1.fasta haplotype_1.unwrapped.fasta
unwrap_fasta haplotype_2.fasta haplotype_2.unwrapped.fasta
grep -A1 ">HiC_scaffold_1$" haplotype_1.unwrapped.fasta > haplotype_1.chr1.fasta
grep -A1 ">HiC_scaffold_1$" haplotype_2.unwrapped.fasta > haplotype_2.chr1.fasta

# stats!
module purge
conda activate base
assemblathon_stats.pl haplotype_1.chr1.fasta | tee haplotype_1.chr1.fasta.assemblathon_stats
assemblathon_stats.pl haplotype_2.chr1.fasta | tee haplotype_2.chr1.fasta.assemblathon_stats

### dotplot 
module purge
ml mummer
nucmer -c 100 -p nucmer -t 4 haplotype_1.chr1.fasta haplotype_2.chr1.fasta

#mv nucmer.delta female2male.nucmer.delta

show-coords -r -c -l nucmer.delta > nucmer.masked.coords

#mummerplot --png female2male.nucmer.delta
mummerplot --png --size large -p female_haplotypes -f nucmer.delta


##################### alternative programs to visualize variants: SAMPLOT, PLOTSR, GENEBASE
