#!/bin/bash
#SBATCH -p general
#sbatch -J Tree_merge
#SBATCH --cpus-per-task=4
#SBATCH -t 4-0:00:00
#SBATCH --mem=40g
#SBATCH -o tree.merge_%j.out

module purge
. ${PROJ}/software/anaconda3/etc/profile.d/conda.sh
conda activate base

cd ${SCR}/longipalpis_ms/phased/iqtree
mkdir consensus_trees
# cat all trees
cat *.contree > consensus_trees/whole_genome_newick.contree
# cat just chr 1
cat HiC_scaffold_1_*.contree > consensus_trees/chr1_newick.contree

cd consensus_trees

# run astral to merge
java -jar ${PROJ}/software/Astral/astral.5.7.8.jar -i whole_genome_newick.contree -o whole_genome_output_consensus.newick
java -jar ${PROJ}/software/Astral/astral.5.7.8.jar -i chr1_newick.contree -o chr1_output_consensus.newick



#### do autosomes only
cd ..
# cat just autosomes
cat HiC_scaffold_2_*.contree HiC_scaffold_3_*.contree HiC_scaffold_4_*.contree > consensus_trees/autosomes_newick.contree


cd consensus_trees

# run astral to merge
java -jar ${PROJ}/software/Astral/astral.5.7.8.jar -i autosomes_newick.contree -o autosome_output_consensus.newick
